# Generated by Django 5.0.7 on 2024-08-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_number', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('time_existence', models.CharField(choices=[('-6', 'Less than 6 months'), ('+6', 'More than 6 months'), ('+1', 'More than 1 year'), ('+5', 'More than 5 years')], default='-6', max_length=2)),
                ('description', models.TextField()),
                ('end_capture_date', models.DateField()),
                ('percent_equity', models.IntegerField()),
                ('stage', models.CharField(choices=[('I', 'I only have an idea'), ('MVP', 'I have an MVP'), ('MVPP', 'I have an MVP with paying customers'), ('E', 'Company ready to scale')], default='I', max_length=4)),
                ('area', models.CharField(choices=[('ED', 'Ed-tech'), ('FT', 'Fintech'), ('HC', 'Health-tech'), ('BI', 'Bio-tech'), ('IT', 'IT Services'), ('RE', 'Real Estate'), ('EN', 'Energy'), ('AI', 'AI/ML'), ('SA', 'SaaS')], max_length=3)),
                ('target_market', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pitch', models.FileField(upload_to='pitches')),
                ('logo', models.FileField(upload_to='logos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
