# Generated by Django 5.0.7 on 2024-08-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='documents')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.company')),
            ],
        ),
    ]
